### ISSUE TITLE
UTMFW not interceting SSLPROXY requests

### ISSUE THREAD

**Issue by pleoeter** [sonertari/SSLproxy#6]
I have installed and configured UTMFW , in the victim machine I have redirected traffic to UTMFW, in the packet filter logs, it does not resolve DNS of the victim machine, instead blocks its request for DNS. I cannot see any connection to SSLProxy as well, 

When I turn off packetfilter DNS is resolved and still no connection to sslproxy, someone please tell me the hierarchy to use the UTMFW services for SSLPROXY

**Comment by sonertari** [comment]
The usual use case for UTMFW is:

	local network <--> UTMFW <--> Internet or external network

If you have successfully installed UTMFW, a computer on the local network should be able to get an IP address from UTMFW and connect to, say, a web server on the Internet, over http or https; in the latter case SSLproxy is used to decrypt and divert traffic to the web filter running on UTMFW. Make sure you have installed the ca.crt of SSLproxy on your web browser (or other clients like MUAs). The packet filter rules and DNS configuration should work without any problems in this case.

I suspect that there is an issue with your network setup. For example,

- Is the external interface of UTMFW configured correctly? If it obtains its IP address and configuration over DHCP, is it correct? The $ext_if macro in the pf ruleset depends on the external IP address of UTMFW, so the DHCP server on the external network should be running when UTMFW is starting, or else the pf rules will not work as expected.
- The DNS configuration should match with the external and internal interface configuration. Is the IP address of the internal interface the same as the "Listen on" address of DNS? Is the gateway address of the external interface is the same as the "Forwarders" address of DNS?
- Also, if you change any interface configuration on the System>Config>Network page, you should run "Automatic config" on System>Config>Init page, and restart the system. This is necessary as many UTM services depend on those network settings.

This is all I can say unless you share more information on what you are trying to do, as I have asked before. For example, I don't understand the phrase "the hierarchy to use the UTMFW services for SSLPROXY". (Currently, there are 4x UTM services using SSLproxy: Web Filter + HTTP proxy, POP3 proxy, SMTP proxy, and IPS. One can say that anti-virus and anti-spam software use it too, because those 4x UTM services make use of anti-virus and anti-spam.)
